### ISSUE TITLE
Option to not display the + when moused over a power pole

### ISSUE THREAD

**Issue by kbrantley** [raeon/Induction_Charging#2]
First off, I really like the mod and the code quality really shows the effort that has gone into it. I like the balancing and pretty much everything about it.

I've tried to add a new per-user setting but am pretty new to factorio mods (not new to lua, though). The specific thing I was/am trying to change is the visibility of the + that appears at the player's feet when standing in a power field and moused over a power pole.

First I tried the per-user setting, I couldn't figure out how to reference the user setting in the appropriate context. I then switched to a global setting (not ideal), and updated Tracker:ShouldHide() to reference this setting. When I set the flag accordingly though, charging was completely disabled, which is not the goal.

So, would you mind pointing me in the right direction as to how I could accomplish this?

**Comment by raeon** [comment]
Hi! First off, thanks for the kind words and the PR! I can't say I think the code _looks_ nice, but it's mostly the product of incremental development, for better or for worse. :-)
I'd like to also apologise for not responding sooner, I've been quite busy but should have more time on my hands now!

Now, regarding your question. As you might have figured out by now, the blue plus is actually _not_ a plus, but rather the four corners of an invisible rectangle with blue corners all squished into one (since the rectangle has zero width/height). This rectangle is typically drawn around entities that interact with the power network in one way or another, and is only shown when, as you mentioned, you hover over one of these entities that use the power network.

As you might've seen while reading through the source code, the mod works by spawning an invisible `electric-energy-interface` entity which follows the player around. This entity is used to draw an exact amount of power form the network. There's a few ways that I can think of off the top of my head that this issue could be resolved:

1. If we know when the player is hovering over them, we could remove the entity. This has the unfortunate side-effect of stopping power transfer during that time.
2. Somehow prevent the rectangle from rendering around this entity.

As a matter of fact, point 1 **is already implemented** as far as possible within the Factorio API. Whenever a player is holding some form of power pole in their hand (as if they were about to place them), then their personal entity is hidden. This has the unfortunate side-effect of disabling charging at that time, as you've found out. In a multiplayer scenario however, you are still able to see other players' entities unless they were also holding a power pole of some form. Note that even _if_ we knew how to know when a player is hovering over a power pole, then which entities would we disable? Only theirs? The entities of all players? There's no real good solution here.

As for point 2, I'm sorry to say there is also no way to do this currently.

I hope my explanation suffices! Thanks again for the PR. I'm closing the issue since there's no real fix, but feel free to reply here with any questions or open a new issue for other things you run into. :-)
